title = "Wiro World"
description = "Milo's own place to post tech stuff and opinions"
base_url = "https://mrnossiom.github.io"

default_language = "en"
generate_feed = true
build_search_index = true
feed_filename = "atom.xml"
taxonomies = [
  { name = "tags" },
]

compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
author = "Milo Moisson"

post_view_navigation_prompt = "Next"
accent_color = "red"
logo_text = "Milo Moisson"
page_titles = "combined"

menu_items = [
  { name = "home", url = "$BASE_URL/" },
  { name = "about me", url = "$BASE_URL/about" },
  { name = "blog", url = "$BASE_URL/blog" },
  { name = "tags", url = "$BASE_URL/tags" },

  { name = "github", url = "https://github.com/mrnossiom", newtab = true },
]

[translations]
summary = "My blog"

[languages.fr]
title = "Wiro World"

generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags" },
]

[languages.fr.translations]
summary = "Mon blog"

# TODO: doesn't seem to be picked up
[languages.fr.extra]
menu_items = [
  { name = "accueil", url = "$BASE_URL/" },
  { name = "à propos", url = "$BASE_URL/about" },
  { name = "blog", url = "$BASE_URL/blog" },
  { name = "tags", url = "$BASE_URL/tags" },

  { name = "github", url = "https://github.com/mrnossiom", newtab = true },
]

