title = "Wiro World"
author = "Milo Moisson"
description = "Milo's own place to post tech stuff and opinions"
base_url = "https://mrnossiom.github.io"

generate_feed = true
feed_filename = "atom.xml"

compile_sass = true

taxonomies = [
  # Tags (e.g. Rust, NixOS)
  { name = "tags", feed = true },
  # TODO Categories (e.g. dev, perso, misc)
  # { name = "categories", feed = false },
]

[languages.fr]
title = "Wiro World"
author = "Milo Moisson"
description = "La place publique de Milo sur des sujets techniques ou des opinions"

generate_feed = true
feed_filename = "atom.xml"

build_search_index = true
compile_sass = true

taxonomies = [
  { name = "tags", feed = false },
]

[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
logo_text = "Milo Moisson"

edit_page_base = "https://github.com/mrnossiom/mrnossiom.github.io/edit/main/content/"

menu_items = [
  { key = "home", url = "/" },
  { key = "about", url = "/about" },
  { key = "posts", url = "/posts" },
  { key = "projects", url = "/projects" },
  { key = "tags", url = "/tags" },
  { key = "archive", url = "/archive" },

  { name = "github", url = "https://github.com/mrnossiom", newtab = true },
]

[translations]
all_tags = "all tags"
show_all_tags = "Show all tags"

lang-switch = "Change to french"
theme-switch = "Change theme"
theme-reset = "Reset to detected theme"

edit_page_github = "Edit/Correct this page on GitHub"
read_more = "Read more"

menu_item-home = "home"
menu_item-about = "about me"
menu_item-posts = "posts"
menu_item-projects = "projects"
menu_item-tags = "tags"
menu_item-archive = "archive"

# French stuff

[languages.fr.translations]
all_tags = "tous les tags"
show_all_tags = "Afficher tous les tags"

lang-switch = "Passer en anglais"
theme-switch = "Changer de theme"
theme-reset = "Revenir au theme automatique"

edit_page_github = "Éditer/Corriger cette page sur GitHub"
read_more = "Lire plus"

menu_item-home = "accueil"
menu_item-about = "à propos"
menu_item-posts = "publications"
menu_item-projects = "projets"
menu_item-tags = "tags"
menu_item-archive = "archive"

