[[language]]
name = "html"
auto-format = false

[[language]]
name = "markdown"
language-servers = [ "ltex-ls", "wakatime" ]

[language-server.ltex-ls.config.ltex]
language = "auto"
[language-server.ltex-ls.config.ltex.dictionary]
en-US = ["dotfiles"]
